name: Release Demo
on:
  push:
    tags:
      - "v1"
    branches:
      - main
  pull_request:
    tags:
      - "v1"
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          owner: "Eduard Gevorkyan"
          omitBody: true
          name: Demo
          omitPrereleaseDuringUpdate: true
          omitBodyDuringUpdate: true
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/amd64, linux/arm64, windows/amd64, darwin/amd64, darwin/arm64
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64]
        exclude:
          - goarch: "386"
            goos: linux
          - goarch: "386"
            goos: windows
          - goarch: "386"
            goos: darwin
          - goarch: arm64
            goos: windows
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.22
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          #As go version I can use values: 1.13, 1.14, 1.15, 1.16, 1.17 or url https://dl.google.com/go/go1.13.1.linux-amd64.tar.gz
          goversion: 1.17
          project_path: "./cmd/main"
          binary_name: "demo"
          executable_compression: upx
          overwrite: TRUE
          sha256sum: TRUE
          release_tag: v1